# Generated by Django 5.2.8 on 2025-11-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_radius_km',
            field=models.FloatField(default=50.0, help_text='Maximum travel distance in km'),
        ),
    ]
