# Generated by Django 5.2.8 on 2025-11-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash on Delivery')], default='CASH', max_length=20),
        ),
    ]
