# Generated by Django 5.2.8 on 2025-11-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
