# Generated by Django 5.2.8 on 2025-11-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_providerprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='working_end',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='working_start',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
