# Generated by Django 5.2.8 on 2025-11-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_providerprofile_working_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, default='covers/default_cover.jpg', null=True, upload_to='covers/'),
        ),
    ]
