# Generated by Django 5.2.8 on 2025-11-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
