# Generated by Django 5.2.8 on 2025-11-28 03:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
